settings:
  drop-items: false # If true, players will drop their items
  double-jump: true # If true, players will be able to double jump
  spawn:
    world: world
    x: 0
    y: 100
    z: 0
    yaw: 0
    pitch: 0
